image: maven:3.9.9-openjdk-17.0.14
default:
  tags:
    - macJumanji
stages:
  - test
Integration test with allure:
  stage: test
  script:
    - java -version
    - mvn -v
    - mvn clean test
    - mvn allure:report
  artifacts:
    paths:
      - target/allure-results